apiVersion: v2
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
# giantswarm app version
version: CHART_VERSION_PLACEHOLDER
name: whereabouts
description: A CNI IPAM plugin that assigns IP addresses cluster-wide
home: https://github.com/giantswarm/whereabouts
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.upstream-chart-url: "https://github.com/k8snetworkplumbingwg/whereabouts/deployment/whereabouts-chart"
  io.giantswarm.application.upstream-chart-version: "APP_VERSION_PLACEHOLDER"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
dependencies:
  - name: whereabouts-crds
    version: CRD_VERSION_PLACEHOLDER
sources:
  - https://github.com/k8snetworkplumbingwg/whereabouts
